# docs are built automatically by a github webhook:
# https://github.com/BlueBrain/NeuroM/settings/hooks
#
# configuration of the docs is is here:
# https://readthedocs.org/projects/neurom/
# One can view the logs, and set properties there.
#
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details on
# this file

version: 2

sphinx:
  configuration: doc/source/conf.py

python:
  version: 2
  install:
    - method: pip
      path: .
    - requirements: requirements_docs.txt
  system_packages: true
